import Head from 'next/head'
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import { Provider, useSelector } from "react-redux";
import { io } from 'socket.io-client'
import { useDispatch } from 'react-redux';
import { addSocket } from '../redux/slices/slice';
import { motion } from 'framer-motion'

export default function Home() {
  const router = useRouter()
  const state = useSelector((state) => state.adminState)
  console.log({ state });
  const dispatch = useDispatch()
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{
        type: "spring",
        stiffness: 260,
        damping: 20,
      }}
      className='bg-purple-500 h-screen'>
      <Head>
        <title>Home | Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>welcome</h1>

    </motion.div>
  )
}

