import Head from 'next/head'
const alanKey = 'c411c68b1472d0c9b61616ccb9a09ec72e956eca572e1d8b807a3e2338fdd0dc/stage'
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import { Provider, useSelector } from "react-redux";
import { MessengerChat } from "react-messenger-chat-plugin";
const pageID = '108679325425567'
const appID = '501714114397260'
export default function Home() {
  const router = useRouter()
  const state = useSelector((state) => state.adminState)
  console.log({ state });
  useEffect(() => {
    const alanBtn = require('@alan-ai/alan-sdk-web');
    alanBtn({
      key: alanKey,
      onCommand: ({ command }) => {
        if (command === 'introduce me') {
          alert('i received command')
        }
        if (command === 'about page') {
          router.push('/about')
        }
        if (command === 'go back') {
          router.back()
        }
      }
    });
  }, []);
  return (
    <div>
      <Head>
        <title>Home | Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MessengerChat
    pageId={pageID}
    language="sv_SE"
    themeColor={"#000000"}
    bottomSpacing={300}
    loggedInGreeting="loggedInGreeting"
    loggedOutGreeting="loggedOutGreeting"
    greetingDialogDisplay={"show"}
    debugMode={true}
    onMessengerShow={() => {
      console.log("onMessengerShow");
    }}
    onMessengerHide={() => {
      console.log("onMessengerHide");
    }}
    onMessengerDialogShow={() => {
      console.log("onMessengerDialogShow");
    }}
    onMessengerDialogHide={() => {
      console.log("onMessengerDialogHide");
    }}
    onMessengerMounted={() => {
      console.log("onMessengerMounted");
    }}
    onMessengerLoad={() => {
      console.log("onMessengerLoad");
    }}
  />
      <h1>welcome</h1>

    </div>
  )
}
